# Generated by Django 6.0.4 on 2026-04-21 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '示例',
                'verbose_name_plural': '示例列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('description', models.TextField(blank=True, verbose_name='品牌描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '水品牌',
                'verbose_name_plural': '水品牌列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='客户编号')),
                ('name', models.CharField(max_length=200, verbose_name='姓名地址')),
                ('open_date', models.DateField(verbose_name='开户日期')),
                ('last_delivery_date', models.DateField(blank=True, null=True, verbose_name='最后送水日期')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, verbose_name='详细地址')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='api.waterbrand', verbose_name='水品牌')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
