# Generated by Django 6.0.4 on 2026-04-21

from django.db import migrations


def create_initial_data(apps, schema_editor):
    """创建初始测试数据"""
    WaterBrand = apps.get_model('api', 'WaterBrand')
    Customer = apps.get_model('api', 'Customer')
    
    # 创建水品牌
    brand1 = WaterBrand.objects.create(
        name='怡宝',
        description='华润怡宝纯净水',
        is_active=True
    )
    
    brand2 = WaterBrand.objects.create(
        name='农夫山泉',
        description='农夫山泉天然水',
        is_active=True
    )
    
    brand3 = WaterBrand.objects.create(
        name='百岁山',
        description='百岁山天然矿泉水',
        is_active=True
    )
    
    # 创建客户
    Customer.objects.create(
        id='0001',
        name='张三 - 北京市朝阳区xxx小区1号楼101',
        brand=brand1,
        open_date='2024-01-15',
        last_delivery_date='2024-04-20',
        phone='13800138001',
        address='北京市朝阳区xxx小区1号楼101',
        remark='老客户',
        is_active=True
    )
    
    Customer.objects.create(
        id='0002',
        name='李四 - 北京市海淀区yyy花园2号楼202',
        brand=brand2,
        open_date='2024-02-20',
        last_delivery_date='2024-04-19',
        phone='13800138002',
        address='北京市海淀区yyy花园2号楼202',
        remark='',
        is_active=True
    )
    
    Customer.objects.create(
        id='0003',
        name='王五 - 北京市西城区zzz大厦3号楼303',
        brand=brand3,
        open_date='2024-03-10',
        last_delivery_date='2024-04-18',
        phone='13800138003',
        address='北京市西城区zzz大厦3号楼303',
        remark='VIP客户',
        is_active=True
    )
    
    Customer.objects.create(
        id='0004',
        name='赵六 - 北京市东城区aaa公寓4号楼404',
        brand=brand1,
        open_date='2024-03-25',
        last_delivery_date='2024-04-17',
        phone='13800138004',
        address='北京市东城区aaa公寓4号楼404',
        remark='',
        is_active=True
    )
    
    Customer.objects.create(
        id='0005',
        name='孙七 - 北京市丰台区bbb家园5号楼505',
        brand=brand2,
        open_date='2024-04-01',
        last_delivery_date='2024-04-16',
        phone='13800138005',
        address='北京市丰台区bbb家园5号楼505',
        remark='新客户',
        is_active=True
    )


def remove_initial_data(apps, schema_editor):
    """删除初始测试数据"""
    Customer = apps.get_model('api', 'Customer')
    WaterBrand = apps.get_model('api', 'WaterBrand')
    
    Customer.objects.all().delete()
    WaterBrand.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, remove_initial_data),
    ]
