# Generated by Django 6.0.4 on 2026-04-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('vip', 'VIP客户'), ('normal', '普通客户'), ('pickup', '自提客户')], default='normal', max_length=10, verbose_name='客户类型'),
        ),
    ]
