# Generated by Django 6.0.4 on 2026-04-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_customer_type'),
    ]

    operations = [
    ]
