# Generated by Django 6.0.4 on 2026-04-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260423_1517'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='api_customer',
        ),
    ]
