# Generated by Django 6.0.4 on 2026-04-24 08:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_customer_number_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=api.models.generate_customer_id, max_length=20, primary_key=True, serialize=False, verbose_name='客户编号'),
        ),
    ]
