# Generated by Django 6.0.4 on 2026-04-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customer_customer_number_alter_customer_id'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE api_customer DROP COLUMN customer_number;", ""),
    ]