# Generated by Django 6.0.4 on 2026-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customer_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='storage_amount',
            field=models.IntegerField(default=0, verbose_name='存水量'),
        ),
    ]
