# Generated by Django 6.0.4 on 2026-04-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customer_storage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owed_empty_bucket',
            field=models.IntegerField(default=0, verbose_name='欠空桶'),
        ),
    ]
