# Generated by Django 6.0.4 on 2026-04-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customer_owed_empty_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
