# Generated by Django 6.0.4 on 2026-04-25 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='open_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='开户日期'),
        ),
    ]
