# Generated by Django 6.0.4 on 2026-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customer_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_water_usage',
            field=models.IntegerField(default=0, verbose_name='总用水量'),
        ),
    ]
