# Generated by Django 6.0.4 on 2026-04-30 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customer_vip_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('water_delivered', models.IntegerField(default=0, verbose_name='送水量')),
                ('buckets_returned', models.IntegerField(default=0, verbose_name='回桶数')),
                ('owed_empty_buckets', models.IntegerField(default=0, verbose_name='欠空桶')),
                ('storage_amount', models.IntegerField(default=0, verbose_name='存水量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='api.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '送水记录',
                'verbose_name_plural': '送水记录列表',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
