# Generated by Django 6.0.4 on 2026-04-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_deliveryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('vip', '套餐客户'), ('normal', '普通客户'), ('pickup', '自提客户'), ('closed', '已注销'), ('slow_pay', '收款慢'), ('blacklist', '黑名单')], default='normal', max_length=10, verbose_name='客户类型'),
        ),
    ]
