# Generated by Django 6.0.4 on 2026-05-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_customer_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='消费总额'),
        ),
        migrations.AddField(
            model_name='waterbrand',
            name='price_per_bucket',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='每桶单价'),
        ),
    ]
