# Generated by Django 6.0.4 on 2026-05-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_customer_total_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_per_bucket',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='桶装水价格'),
        ),
    ]
