# Generated by Django 6.0.4 on 2026-05-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_customer_price_per_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbrand',
            name='brand_type',
            field=models.CharField(choices=[('bucket', '桶装水'), ('bottle', '支装水'), ('disposable', '一次性桶装水')], default='bucket', max_length=20, verbose_name='品牌类型'),
        ),
    ]
