# Generated by Django 6.0.4 on 2026-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_waterbrand_brand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbrand',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='进货价'),
        ),
        migrations.AlterField(
            model_name='waterbrand',
            name='price_per_bucket',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='零售价'),
        ),
    ]
