# Generated by Django 6.0.4 on 2026-05-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_waterbrand_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbrand',
            name='specification',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='规格'),
        ),
    ]
