# Generated by Django 6.0.4 on 2026-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_waterbrand_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='floor_type',
            field=models.CharField(choices=[('default', '默认'), ('elevator', '电梯'), ('stair', '步梯'), ('residential', '住宅')], default='default', max_length=20, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='customer',
            name='stair_extra_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='步梯加收费用'),
        ),
    ]
