# Generated by Django 6.0.4 on 2026-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_customer_floor_type_customer_stair_extra_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('wechat', '微信'), ('internet', '互联网'), ('phone', '电话')], default='wechat', max_length=20, verbose_name='客户来源'),
        ),
    ]
